name: Lint GDScript
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gdlint:
    name: Run gdlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install gdtoolkit
        run: pip install gdtoolkit

      - name: Run gdlint on addons
        run: gdlint addons/godot_with_u/
