name: Release Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Addon
        run: |
          mkdir -p release
          cd addons
          zip -r ../release/GodotWithU.zip godot_with_u/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/GodotWithU.zip
          generate_release_notes: true
